#!/bin/bash
echo DEBUG script, connects to localhost, writes in /tmp/irclogger-logs

# host[:port]
host=${IRCLOGGER_DEBUG_HOST:-localhost}
logsdir="${IRCLOGGER_DEBUG_DIR:-/tmp/irclogger-logs}"
url="http://localhost/irclogger-logs"
channels="${IRCLOGGER_DEBUG_CHAN:-irclogger-test}"
# Uncomment this if the IRC server has a password (and put the relevant passwd)
export IRC_SERVER_PASSWORD="${IRCLOGGER_DEBUG_PASS}"
nickname="${IRCLOGGER_DEBUG_NICK:-[IRCLOGGER_D]}"

mkdir -p $logsdir
    if test -e "$logsdir/CHANNELS.last"; then
	channels=`cat "$logsdir/CHANNELS.last"`
    fi
    echo "Starting at `date`, logging channels $channels" 
    ./ircloggerd $host "$nickname" \
	"$logsdir" "$url" $channels>>"$logsdir/irclogger.log"
    echo "Stopping at `date`"
chmod -R a+rwX $logsdir 2>/dev/null
