#!/bin/bash
set -a
. bashlib
. irclogger_common
CHAN=${PATH_INFO#/}

search=`param search`
action=`param action`
grep=`param grep`
grepck=;egrepck=;fgrepck=
case "$grep" in on)grepck=checked;;e|'')egrepck=checked;;f)fgrepck=checked;;
esac
if [ -n "`param case`" ]; then case=''; else case=i
fi
STYLE=
cd $logsdir
if [ -e style.css ]; then STYLE="`cat style.css`";fi
cd $logsdir/$CHAN
if [ -e style.css ]; then STYLE="$STYLE`cat style.css`";fi

form () {
  echo "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML//EN\">
<html>
<head>
<title>#$CHAN irc log search</title>
<style type='text/css'> $STYLE </style>
</head>
<body>
<h1>#$CHAN irc log search</h1>
$locked
<a href='${SCRIPT_NAME%/*}/irclogger_logs/$CHAN'>back</a>
<form>
  <input type=text name=search value='$PREVSEARCH' size=32>
  <input type=submit value=Search>
  <input type=hidden name=action value=search> by 
  <input type=radio name=grep value=e $egrepck>egrep
  <input type=radio name=grep $grepck>grep
  <input type=radio name=grep value=f $fgrepck>fgrep
  <br><input type=checkbox name=case>Case sensitive
<br>
</form>
$RESULTS
</body></html>"
}

main () {
  if acces_protected "$CHAN"; then locked="$private_image<p>";else locked=
  fi
  if [ "$action" = "search" ]; then
    RESULTS=`search "$search"`
    PREVSEARCH="$search"
  else
    RESULTS=
  fi
  echo "Content-type: text/html"; echo ""
  form
  exit 0
}

search () {
  echo '<hr><h2>Results:</h2>'
  z${grep}grep -n$case "$search" /dev/null `ls -1r *log*` | ( ofile='';matches=0; files=0
    while read line; do
      file="${line%%:*}";rest="${line#*:}";num="${rest%%:*}";rest="${rest#*:}"
      if [ "$ofile" != "$file" ]; then echo "<br><b>${file%.log*}</b>"
	let files=files+1
      fi
      ofile="$file"
      date="${file%.log*}"
      let num1=num-4
      echo "<br>&nbsp;<a href=${SCRIPT_NAME%/*}/irclogger_log/$CHAN?date=${date}&sel=$num#l$num1>$num</a>&nbsp;<small>"
      echo "$rest"|sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g'
      echo "</small>"
      let matches=matches+1
    done
    echo "<hr><b>$matches</b> matches in $files files"
    )
}

main
### EMACS MODES
### Local Variables: ***
### mode:ksh ***
### End: ***
