#!/bin/bash
# $1=channel $2=date('%Y-%m-%d,%a') $3=selected_line $4=config_file $5=header
# $6=filename
set -a
shopt -s extglob

CHAN=$1
if test -e "$4"; then conffile="$4"; . "${conffile%/*}/irclogger_common"
else logsdir=${logsdir:-/var/log/irclogger}
fi

case "$6" in /*)logfile="$6";; *)logfile="$PWD/$6";;
esac
cd $logsdir

omn=-100
owho=""
iseven=true

eol=""

grep '^[[][0-9][0-9]:[0-9][0-9][]] <' |\
sed -e 's/^[[][0-9][0-9]:[0-9][0-9][]] <[^>]*> //'

exit 0
### EMACS MODES
### Local Variables: ***
### mode:ksh ***
### End: ***
