#!/bin/bash
set -a
. bashlib
. irclogger_common

CHAN=${PATH_INFO#/}
STYLE=
cd $logsdir
if [ -e style.css ]; then STYLE="`cat style.css`";fi
cd $logsdir/$CHAN
if [ -e style.css ]; then STYLE="$STYLE`cat style.css`";fi

pass="$FORM_pass"

main() {
  if acces_protected "$CHAN" 
  then action=change
  else
    if protectable "$CHAN"
    then action=set
    else echo "Location: ${SCRIPT_NAME%/*}/irclogger_logs/$CHAN";echo
      exit 0
    fi
  fi
  if [ -z "$pass" ]
  then show_form "$CHAN"
  else perform_password_change "$CHAN" "$pass"
  fi
}

show_form () {
  echo "Content-type: text/html; charset: ISO-8859-1

<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML//EN\">
<html>
<head>
<title>#$CHAN irc log $action password</title>
<style type='text/css'> $STYLE </style>
</head>
<body>
<h1>#$CHAN irc log $action password</h1>
<a href='${SCRIPT_NAME%/*}/irclogger_logs/$CHAN'>back</a>
<form>
  <input type=text name=pass size=32>
  <input type=submit value='Set new password'>
</form>
</body></html>"
}

perform_password_change () {
  echo "Content-type: text/html; charset: ISO-8859-1

<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML//EN\">
<html>
<head>
<title>#$CHAN irc log $action password</title>
<style type='text/css'> $STYLE </style>
</head>
<body>
<h1>#$CHAN irc log $action password</h1>
<a href='${SCRIPT_NAME%/*}/irclogger_logs/$CHAN'>back</a>
<p>Changing passwords:
<pre>"
  htpasswd -b $passfile "$1" "$2" 2>&1
  htpasswd -b $passfile "#$1" "$2" 2>&1
  echo "</pre>
Done.</body></html>"
}

main

### EMACS MODES
### Local Variables: ***
### mode:ksh ***
### End: ***
