#!/bin/bash
USAGE='generates a version and uploads it on my web distribution dir
that must be in $files_repository (ssh syntax)'

if test -z "$files_repository"; then echo "$USAGE"; exit 1; fi

name=irclogger
dir=/tmp/$name.$$
rev=`grep '^[0-9][.][0-9]' HISTORY.txt |head -1|sed -e 's/ .*//'`
repo=$files_repository/$name

mkdir -p $dir/$name
cp -a * $dir/$name
cd $dir
tar cfz /tmp/$name-$rev.tgz $name
cd /tmp
echo "## Ok, distribution made: `ls -sh $name-$rev.tgz`"
echo "## Uploading to $repo"
if scp -C $name-$rev.tgz $repo/$name-$rev.tgz; then
  echo "## Ok, at $files_repository_url/$name/$name-$rev.tgz"
else
  echo "***** UPLOADING ERROR !!! *****"
fi

rm -rf $dir /tmp/$name-$rev.tgz
