#!/bin/bash
# this script converts IRC logs from the xchat format to the mirc one used 
# by irclogger
# takes xchat2 logs on input, writes mirc logs, one file per day
# named YYYY-MM-DD,Day.log: e.g: 2006-11-23,Thu.log

main () {
  grep '^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] [[][0-9][0-9]:[0-9][0-9][]]' | \
  while read date time who text; do
    case "$text" in [[][oO][fF][fF][]]*) continue;; esac
    if test x"$who" = 'x<--' -o x"$who" = 'x-->'; then
      who='***'
    fi
    day=`date -d $date +'%a'`
    echo "$time $who $text" >>$date,$day.log
  done
}

main
